# Generated by Django 4.1.1 on 2022-09-12 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_rename_article_image_article_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='images',
            new_name='article_image',
        ),
    ]
